repository_type: pipeline

nf_core_version: 4.1.0

lint:
  files_unchanged:
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/branch.yml
    - .github/workflows/pr-comment.yml
    - .github/workflows/linting.yml
    - .github/.dockstore.yml
    - .prettierignore
    - assets/sendmail_template.txt
    - docs/CONTRIBUTING.md
    - CODE_OF_CONDUCT.md
    - assets/nf-core-fluab_reference_db_logo_light.png
    - docs/images/nf-core-fluab_reference_db_logo_light.png
    - docs/images/nf-core-fluab_reference_db_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.txt
    - docs/README.md
  nextflow_config:
    - manifest.name
    - manifest.homePage
  multiqc_config: false
  files_exist:
    - CITATIONS.md
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/.dockstore.yml
    - docs/CONTRIBUTING.md
    - assets/multiqc_config.yml
    - CODE_OF_CONDUCT.md
    - assets/nf-core-fluab_reference_db_logo_light.png
    - docs/images/nf-core-fluab_reference_db_logo_light.png
    - docs/images/nf-core-fluab_reference_db_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config
  readme:
    - nextflow_badge
    - nfcore_template_badge
    - nextflow_badge

template:
  org: provlab-bioinfo
  name: fluab_reference_db
  description: Process to create databases for nf-fluab
  author: Xiaoli-dong
  version: 0.1.0
  force: true
  outdir: ./fluab-reference-db
  skip_features:
    - github
    - github_badges
    - igenomes
    - multiqc
    - fastqc
    - seqera_platform
    - gpu
    - codespaces
    - vscode
    - citations
    - rocrate
  is_nfcore: false
